server:
  port: 8001

spring:
  application:
    name: security-jjwt

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 951209
  resources:
    static-locations: classpath:/static/,classpath:/templates/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/
  thymeleaf:
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/


mybatis:
  type-aliases-package: cn.ga.securityjjwt.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
